import { expect, test } from "@playwright/test"

test("個別URL・自動ID発行・再表示・別トライアルへの切替", async ({ page, browser }) => {
  // テスト用ローカル環境だけで作る運営アカウント。本番アカウントにはアクセスしない。
  await page.goto("/?tab=settings")
  await page.getByLabel("メールアドレス").fill("owner@example.test")
  await page.getByLabel("パスワード").fill("local-e2e-owner-pass")
  await page.getByRole("button", { name: "ログイン", exact: true }).click()
  await page.getByRole("button", { name: "トライアルを発行", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await dialog.getByLabel("渡し先の名前").fill("E2Eお客様")
  await dialog.getByText("お客様", { exact: true }).click()
  await expect(dialog.getByLabel(/ログイン ID/)).toHaveCount(0)
  const issuedResponse = page.waitForResponse(r => r.url().endsWith("/api/demo/trials") && r.request().method() === "POST")
  await dialog.getByRole("button", { name: "発行する", exact: true }).click()
  const issued = (await (await issuedResponse).json()).data
  expect(issued.trial.kind).toBe("PROSPECT_HOTEL")
  expect(new URL(issued.loginUrl).origin).toBe("https://public.example.test")
  await expect(dialog.locator("pre")).toContainText(issued.loginUrl)
  await dialog.getByRole("button", { name: "閉じる", exact: true }).click()
  await page.reload()
  await page.getByRole("button", { name: "ログイン情報", exact: true }).click()
  await expect(dialog.locator("pre")).toContainText(issued.password)
  await expect(dialog.locator("pre")).toContainText(issued.loginUrl)
  await dialog.getByRole("button", { name: "閉じる", exact: true }).click()
  const secondResponse = await page.request.post("/api/demo/trials", { data: { name: "E2E販売店", kind: "DEALER", days: 30 } })
  const second = (await secondResponse.json()).data
  expect(second.loginUrl).not.toBe(issued.loginUrl)
  const guest = await browser.newContext()
  const visitor = await guest.newPage()
  const path = (value: string) => `http://localhost:3100/${new URL(value).search}`
  await visitor.goto(path(issued.loginUrl))
  await expect(visitor.getByLabel("メールアドレス")).toHaveCount(0)
  const forbidden = await visitor.request.get(`/api/demo/trials/${issued.trial.id}`)
  expect(forbidden.status()).toBe(401)
  await visitor.getByLabel("パスワード").fill(issued.password)
  await visitor.getByRole("button", { name: "ログイン", exact: true }).click()
  await expect(visitor.getByRole("button", { name: "ダッシュボード", exact: true }).first()).toBeVisible()
  await visitor.goto(path(second.loginUrl))
  await expect(visitor.getByRole("button", { name: "ログイン", exact: true })).toBeVisible()
  await visitor.getByLabel("パスワード").fill(issued.password)
  await visitor.getByRole("button", { name: "ログイン", exact: true }).click()
  await expect(visitor.getByText(/正しくありません/)).toBeVisible()
  await visitor.getByLabel("パスワード").fill(second.password)
  await visitor.getByRole("button", { name: "ログイン", exact: true }).click()
  await expect(visitor.getByRole("button", { name: "ダッシュボード", exact: true }).first()).toBeVisible()
  await guest.close()
})
